### ISSUE TITLE
Rules: P5 power

### ISSUE THREAD

**Issue by gloinul** [akvik/18Norway#12]
`P5 Carl Abraham Pihl: Public company owning
P5 may nationalize out of turn, i.e. ‘skipping
the line’. Closes when first 5 train is bought.`

This power is unclear. Is the power that a company owning this private may at any time prior to any other company having nationalized in the NR say that it will Nationaliz, even if it is later in the reverse order? May it pass its regular place and nationalize later before another company furhter in the order?

**Comment by akvik** [comment]
Agreed, we will look at this formulation. The meaning is the owner of P5 get to choose before any other company - it gets to say yes or no first, in other words. Only one company get to nationalize in each NR, so this can be crucial. Will make an attempt to make this clearer.
