### ISSUE TITLE
Rules: Section 1.2 For Experienced 18xx players

### ISSUE THREAD

**Issue by gloinul** [akvik/18Norway#14]
Here are mostly editorial parts in this section.

`The stock market is one dimensional, the capitalization
is partial. Double and triple jumps are
possible if conditions are met (see game board).
See game board or Section 8.9.`

Isn't usually the capitalization model called "incremental"?

`At the end of each stock round, stock prices go up
for companies with all stocks not in the Bank
Pool or in their company treasury. Stock prices
go down for each company with stocks in the
Bank Pool. See game board or Section 7.6.`

I would suggest:
... with no stocks in either the Bank
Pool or their company treasury.

`Each mountain hex has a mountain token. To lay
a tile, pay the cost on the hex and keep the
mountain token.`

I would suggest:
 To lay
a tile, pay the cost on the hex and  the
mountain token.

**Comment by akvik** [comment]
Isn't usually the capitalization model called "incremental"?
I've seen it referred to as partial too, but maybe incremental is better - will check.

I would suggest:
... with no stocks in either the Bank
Pool or their company treasury.
Fixed

To lay
a tile, pay the cost on the hex and the
mountain token.
That's inaccurate, they pay the cost on the tile, and then you get to choose to pay the cost on the token to remove it. So it stands, but thanks.
