### ISSUE TITLE
Rules: Overview

### ISSUE THREAD

**Issue by gloinul** [akvik/18Norway#15]
Figure 1:

Should there be an arrow from the second OR to the SR for when in Phase 2? And write Phase 3-D on the OR2 to NR2.

Editorial:
`Companies use their ships and trains to generate
revenue for their owners. After the second OR has
finished, the second SR starts.`

I would suggest:
After the second OR has
finished, the next SR starts.

This as one circulates in this in a number of loops until the game end is triggered.

**Comment by akvik** [comment]
Editorial: Fixed, will upload shortly.

"Should there be an arrow from the second OR to the SR for when in Phase 2? And write Phase 3-D on the OR2 to NR2." Interesting, we should consider it, perhaps. I don't think we've had a problem with the way we're doing it now, but we should put in on the good suggestions list.
