### ISSUE TITLE
Private company revenue

### ISSUE THREAD

**Issue by ollybh** [akvik/18Norway#18]
The revenues for several private companies are different in the rules and on the company cards:

- P2 is shown as 5kr revenue on its card, but the rules show 10kr.
- P4 has 10kr on the card and 15kr in the rules.
- P6 has 15kr on the card and 20kr in the rules.

**Comment by akvik** [comment]
Thanks! Good catch, the rulebook has traces of old rules apparently - the cards are correct. Have updated the rulebook, will upload shortly.
