### ISSUE TITLE
Avoiding never ending games

### ISSUE THREAD

**Issue by gloinul** [akvik/18Norway#28]
When we played our first game we entered the situation that one company was cloased prior to entering phase 5. The company was Bergen which opened up the coast and the S5 become very attractive as one for a single port token could run Trondheim south. Which made ships very profitible and as they are cheaper than the 6-train when having entered phase 5 a lot of ships was bought. Thus train locking the companies. 

From Discord conversation we understand that the rule that closed companies can be re-opened again. We did discuss this further and mostly agree that it appears to solve the issue as it will be attractive to open this company as one can open it as minor company and get three 20% shares for two certificates. However with only one play so far I did wonder if there would be cases one could make the route for a company so unattractive that no one would open that company again? If that would be the case one could have a never ending company. 

The other proposal discussed was to limit the ships such that all companies can't buy ships also avoiding train locking all companies.

**Comment by akvik** [comment]
Yup, we've been working on options here. We're reducing the number of ships and we are also considering permitting companies to open again.
