### ISSUE TITLE
Rules: Clarify order of paying fees when running trains (Section 8.8)

### ISSUE THREAD

**Issue by gloinul** [akvik/18Norway#3]
`The company must pay a 10kr fee from its treasury
in order to run a train to any hex with a mountain
token. This does not affect the revenue of that run.`

If I understand this correctly the company _MUST_ pay first to be able to run that route. So pay first, then run. 

Secondly, the use of ANY makes it unclear if one pays 10 independently of how many mountain hexes or if its _PER_ hex one pays 10.

**Comment by akvik** [comment]
Yup - better to write "each" instead of "any" here. Have rephrased it to specify that this happens prior to the run.
