### ISSUE TITLE
Rule summary

### ISSUE THREAD

**Issue by gloinul** [akvik/18Norway#32]
Something I do really appreciate in 1871 TOP's rule book is the summary of all main rules. This, goes a bit further than the intro summary of the main points, which is missing which issuing rules used for example. 

1871 rules: https://boardgamegeek.com/filepage/237738/top-1871-prototype-rules

**Comment by akvik** [comment]
Yes, we have plans on doing something similar but maybe not as elaborate as 1871 - we have a sequence of play and a short intro for experienced players but it would be cool to make a player aid of some kind.
