### ISSUE TITLE
Rules: Port tokens

### ISSUE THREAD

**Issue by gloinul** [akvik/18Norway#5]
I think the "port token" concept needs an explanation in the introduction or earlier sections to make the rules in Section 8.5-8.7 more easily understood. My understanding is that a company have 4 tokens, one being the home station and the company may lay any token as a port token instead of station token by flipping it over.
- A station token in a port city function as both a station token and a port token.
- A port token can always be placed in a city even if there are no station token slots available.

**Comment by akvik** [comment]
well, that is not entirely correct - we should add a visual example on the tokens, perhaps. There is a specific space on the board for harbor tokens, and they are identical to the station tokens (in fact, it jeopardizes your land presence to invest in harbor tokens). We will look at a way to make this clear with an example.
