### ISSUE TITLE
Rules: Issuing share restriction on 50%

### ISSUE THREAD

**Issue by gloinul** [akvik/18Norway#6]
Section 8.3.1 paragraph "Restriction" appears to be missing a relevant rule. Because I assume that one is in fact not allowed to issue shares so that the bank pool contain more than 50% of the shares?

**Comment by akvik** [comment]
You mean in addition to what it already says? "Restriction: The maximum number of shares that can be issued equals the number of shares not in the company treasury, minus the number of shares in the Bank Pool." I think that formulation also includes the 50% rule for the Bank Pool.
